services:
  postgres:
    container_name: springApp_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "docker_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  postgres-test:
    container_name: springApp_test_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "docker_db_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5434:5432"